### PR TITLE
Implement some more API calls for groups, grouptypes and permissions

### PR DESCRIPTION
**Pull request by fschrempf**
This implements the following API calls:

* `get_groups_hierarchies()` to fetch group hierarchies
* `get_grouptypes()` to fetch group types
* `get_group_permissions()` to fetch permissions of the current user for a given grouo
* `update_group()` to update group data
* `get_global_permissions()` to fetch global permissions of the current user

Solves #72, #73, #74, #75, #76

### CODE REVIEW

**Review by bensteUEM — COMMENTED** [review]
@fschrempf any chance you would also write unittests for the new functions or should I add them as part of the merge?

Furthermore I need to check changes from other branches first (dev_benste)

Do you want a reference link in the contributions section ?

**Comment by fschrempf** [comment]
@bensteUEM Thanks for the fast reply!

> @fschrempf any chance you would also write unittests for the new functions or should I add them as part of the merge?

I looked into it, but I'm hesitating as the test cases often seem to be specific to the test target instance (is https://elkw1610.krz.tools your production instance?). So if I implement tests for my instance they might not work with yours. If you could come up with some tests when merging that would be great!

Do you know if ChurchTools provides a public instance that could be used for running automated tests against? IMHO that would be a good thing for the future. I know you can create a demo instance. Maybe that could be used.

> Furthermore I need to check changes from other branches first (dev_benste)

Sure!

> Do you want a reference link in the contributions section ?

Yes, you could add something like this:

* [fschrempf](https://github.com/fschrempf) - Frieder supporting CVJM Esslingen e. V. (https://cvjm-esslingen.de)

**Comment by bensteUEM** [comment]
Hi, yes I have to admit elkw1610 is our production. 
Some test functions require specific combination of e.g. services or Song categories to be present.
As far as I understood the CT demo instance can be changed by anyone and therefore doesn't offer a stable set of events to test against.

The built process of this repo tests against ours therefore I thought it's easiest to test against it.
Maybe if you do have some time you could draft the tests and I'll swap values and IDs against ours when merging ...

**Comment by fschrempf** [comment]
> As far as I understood the CT demo instance can be changed by anyone and therefore doesn't offer a stable set of events to test against.

It seems like one could use the API Endpoint at https://ccp.church.tools/api/demo to create a demo instance with a new, defined dataset. https://ccp.church.tools/demo shows that there are even data templates to select from. If ChurchTools would provide the templates (preferably in a repo on GitHub) one could write tests against them.

> Maybe if you do have some time you could draft the tests and I'll swap values and IDs against ours when merging ...

Ok, I'll give it a try.

**Comment by fschrempf** [comment]
I pushed some fixup commits for the implementation of the API calls. And I came up with some tests. You need to replace a few ids and values so they work with your instance, but it should be pretty straightforward.

Should I squash the fixup commits into the first commit and do a force push. Or do you want to do it?

**Comment by bensteUEM** [comment]
Feel free to squash. Ideally it would be one commit per function but I suppose its to late for that.
+ I'll add you to the project, this way you can push your branch directly instead of working with a fork

**Comment by fschrempf** [comment]
> Feel free to squash. Ideally it would be one commit per function but I suppose its to late for that.

Ok. I can also separate them into one commit per function + test. Shouldn't be too hard.

> * I'll add you to the project, this way you can push your branch directly instead of working with a fork

Great, thanks!

**Comment by fschrempf** [comment]
I rewrote the history so it is one commit for each function including the unit test.

**Comment by bensteUEM** [comment]
Closed with v1.4.2 release - integrated with minor changes

**Pull request closed without merging**
